export { default as CoinDetails } from './coin-details'
export { default as Splash } from './splash'
export { default as Favourites } from './favourites'
export { default as TrendingCoinsNfts } from './trending-coins-nfts'
export { default as CurrencyConverter } from './currency-converter'
export { default as Search } from './search'
export { default as Exchanges } from './exchanges' 