export const COIN_LIST = [
    { name: 'Bitcoin (BTC)', code: 'bitcoin' },
    { name: 'Ethereum (ETH)', code: 'ethereum' },
    { name: 'XRP (XRP)', code: 'ripple' },
    { name: 'Tether (USDT)', code: 'tether' },
    { name: 'BNB (BNB)', code: 'binancecoin' },
    { name: 'Solana (SOL)', code: 'solana' },
    { name: 'USDC (USDC)', code: 'usd-coin' },
    { name: 'Dogecoin (DOGE)', code: 'dogecoin' },
    { name: 'Lido Staked Ether (STETH)', code: 'staked-ether' },
    { name: 'Cardano (ADA)', code: 'cardano' },
    { name: 'TRON (TRX)', code: 'tron' },
    { name: 'Hyperliquid (HYPE)', code: 'hyperliquid' },
    { name: 'Wrapped Bitcoin (WBTC)', code: 'wrapped-bitcoin' },
    { name: 'Wrapped stETH (WSTETH)', code: 'wrapped-steth' },
    { name: 'Stellar (XLM)', code: 'stellar' },
    { name: 'Sui (SUI)', code: 'sui' },
    { name: 'Chainlink (LINK)', code: 'chainlink' },
    { name: 'Wrapped Beacon ETH (WBETH)', code: 'wrapped-beacon-eth' },
    { name: 'Hedera (HBAR)', code: 'hedera-hashgraph' },
    { name: 'Wrapped eETH (WEETH)', code: 'wrapped-eeth' },
    { name: 'Avalanche (AVAX)', code: 'avalanche-2' },
    { name: 'Bitcoin Cash (BCH)', code: 'bitcoin-cash' },
    { name: 'Shiba Inu (SHIB)', code: 'shiba-inu' },
    { name: 'Litecoin (LTC)', code: 'litecoin' },
    { name: 'LEO Token (LEO)', code: 'leo-token' },
    { name: 'WETH (WETH)', code: 'weth' },
    { name: 'Toncoin (TON)', code: 'toncoin' },
    { name: 'USDS (USDS)', code: 'stableusd' },
    { name: 'Binance Bridged USDT (BSC-USD)', code: 'binance-usd' },
    { name: 'Ethena USDe (USDE)', code: 'ethena-usde' }
];

export const COIN_ICONS = {
    bitcoin: 'https://assets.coingecko.com/coins/images/1/standard/bitcoin.png',
    ethereum: 'https://assets.coingecko.com/coins/images/279/standard/ethereum.png',
    ripple: 'https://assets.coingecko.com/coins/images/44/standard/xrp-symbol-white-128.png',
    tether: 'https://assets.coingecko.com/coins/images/325/standard/Tether.png',
    binancecoin: 'https://assets.coingecko.com/coins/images/825/standard/bnb-icon2_2x.png',
    solana: 'https://assets.coingecko.com/coins/images/4128/standard/solana.png',
    'usd-coin': 'https://assets.coingecko.com/coins/images/6319/standard/usdc.png',
    dogecoin: 'https://assets.coingecko.com/coins/images/5/standard/dogecoin.png',
    'staked-ether': 'https://assets.coingecko.com/coins/images/13442/standard/steth_logo.png',
    cardano: 'https://assets.coingecko.com/coins/images/975/standard/cardano.png',
    tron: 'https://assets.coingecko.com/coins/images/1094/standard/tron-logo.png',
    hyperliquid: 'https://assets.coingecko.com/coins/images/50882/standard/hyperliquid.jpg',
    'wrapped-bitcoin': 'https://assets.coingecko.com/coins/images/7598/standard/wrapped_bitcoin_wbtc.png',
    'wrapped-steth': 'https://assets.coingecko.com/coins/images/18834/standard/wstETH.png',
    stellar: 'https://assets.coingecko.com/coins/images/100/standard/fmpFRHHQ_400x400.jpg',
    sui: 'https://assets.coingecko.com/coins/images/26375/standard/sui-ocean-square.png',
    chainlink: 'https://assets.coingecko.com/coins/images/877/standard/chainlink-new-logo.png',
    'wrapped-beacon-eth': 'https://assets.coingecko.com/coins/images/30061/standard/wbeth-icon.png',
    'hedera-hashgraph': 'https://assets.coingecko.com/coins/images/3688/standard/hbar.png',
    'wrapped-eeth': 'https://assets.coingecko.com/coins/images/33033/standard/weETH.png',
    'avalanche-2': 'https://assets.coingecko.com/coins/images/12559/standard/Avalanche_Circle_RedWhite_Trans.png',
    'bitcoin-cash': 'https://assets.coingecko.com/coins/images/780/standard/bitcoin-cash-circle.png',
    'shiba-inu': 'https://assets.coingecko.com/coins/images/11939/standard/shiba.png',
    litecoin: 'https://assets.coingecko.com/coins/images/2/standard/litecoin.png',
    'leo-token': 'https://assets.coingecko.com/coins/images/8418/standard/leo-token.png',
    weth: 'https://assets.coingecko.com/coins/images/2518/standard/weth.png',
    toncoin: 'https://assets.coingecko.com/coins/images/17980/standard/photo_2024-09-10_17.09.00.jpeg',
    stableusd: 'https://assets.coingecko.com/coins/images/39926/standard/usds.webp',
    'binance-usd': 'https://assets.coingecko.com/coins/images/35021/standard/USDT.png',
    'ethena-usde': 'https://assets.coingecko.com/coins/images/33613/standard/usde.png'
};

export const CURRENCY_LIST = [
    { name: 'Bitcoin (BTC)', code: 'btc' },
    { name: 'Ether (ETH)', code: 'eth' },
    { name: 'Litecoin (LTC)', code: 'ltc' },
    { name: 'Bitcoin Cash (BCH)', code: 'bch' },
    { name: 'Binance Coin (BNB)', code: 'bnb' },
    { name: 'EOS (EOS)', code: 'eos' },
    { name: 'XRP (XRP)', code: 'xrp' },
    { name: 'Lumens (XLM)', code: 'xlm' },
    { name: 'Chainlink (LINK)', code: 'link' },
    { name: 'Polkadot (DOT)', code: 'dot' },
    { name: 'Yearn.finance (YFI)', code: 'yfi' },
    { name: 'Solana (SOL)', code: 'sol' },
    { name: 'US Dollar (USD)', code: 'usd' },
    { name: 'United Arab Emirates Dirham (AED)', code: 'aed' },
    { name: 'Argentine Peso (ARS)', code: 'ars' },
    { name: 'Australian Dollar (AUD)', code: 'aud' },
    { name: 'Bangladeshi Taka (BDT)', code: 'bdt' },
    { name: 'Bahraini Dinar (BHD)', code: 'bhd' },
    { name: 'Bermudian Dollar (BMD)', code: 'bmd' },
    { name: 'Brazil Real (BRL)', code: 'brl' },
    { name: 'Canadian Dollar (CAD)', code: 'cad' },
    { name: 'Swiss Franc (CHF)', code: 'chf' },
    { name: 'Chilean Peso (CLP)', code: 'clp' },
    { name: 'Chinese Yuan (CNY)', code: 'cny' },
    { name: 'Czech Koruna (CZK)', code: 'czk' },
    { name: 'Danish Krone (DKK)', code: 'dkk' },
    { name: 'Euro (EUR)', code: 'eur' },
    { name: 'British Pound Sterling (GBP)', code: 'gbp' },
    { name: 'Georgian Lari (GEL)', code: 'gel' },
    { name: 'Hong Kong Dollar (HKD)', code: 'hkd' },
    { name: 'Hungarian Forint (HUF)', code: 'huf' },
    { name: 'Indonesian Rupiah (IDR)', code: 'idr' },
    { name: 'Israeli New Shekel (ILS)', code: 'ils' },
    { name: 'Indian Rupee (INR)', code: 'inr' },
    { name: 'Japanese Yen (JPY)', code: 'jpy' },
    { name: 'South Korean Won (KRW)', code: 'krw' },
    { name: 'Kuwaiti Dinar (KWD)', code: 'kwd' },
    { name: 'Sri Lankan Rupee (LKR)', code: 'lkr' },
    { name: 'Burmese Kyat (MMK)', code: 'mmk' },
    { name: 'Mexican Peso (MXN)', code: 'mxn' },
    { name: 'Malaysian Ringgit (MYR)', code: 'myr' },
    { name: 'Nigerian Naira (NGN)', code: 'ngn' },
    { name: 'Norwegian Krone (NOK)', code: 'nok' },
    { name: 'New Zealand Dollar (NZD)', code: 'nzd' },
    { name: 'Philippine Peso (PHP)', code: 'php' },
    { name: 'Pakistani Rupee (PKR)', code: 'pkr' },
    { name: 'Polish Zloty (PLN)', code: 'pln' },
    { name: 'Russian Ruble (RUB)', code: 'rub' },
    { name: 'Saudi Riyal (SAR)', code: 'sar' },
    { name: 'Swedish Krona (SEK)', code: 'sek' },
    { name: 'Singapore Dollar (SGD)', code: 'sgd' },
    { name: 'Thai Baht (THB)', code: 'thb' },
    { name: 'Turkish Lira (TRY)', code: 'try' },
    { name: 'New Taiwan Dollar (TWD)', code: 'twd' },
    { name: 'Ukrainian Hryvnia (UAH)', code: 'uah' },
    { name: 'Venezuelan Bolívar (VEF)', code: 'vef' },
    { name: 'Vietnamese Đồng (VND)', code: 'vnd' },
    { name: 'South African Rand (ZAR)', code: 'zar' },
    { name: 'IMF Special Drawing Rights (XDR)', code: 'xdr' },
    { name: 'Silver - Troy Ounce (XAG)', code: 'xag' },
    { name: 'Gold - Troy Ounce (XAU)', code: 'xau' },
    { name: 'Bits (BITS)', code: 'bits' },
    { name: 'Satoshi (SATS)', code: 'sats' }
];

export const CURRENCY_SYMBOLS = {
    btc: '₿',
    eth: 'Ξ',
    ltc: 'Ł',
    bch: 'Ƀ',
    bnb: 'Ⓑ',
    eos: 'ε',
    xrp: '✕',
    xlm: '★',
    link: '🔗',
    dot: '•',
    yfi: 'ɏ',
    sol: '◎',
    usd: '$',
    aed: 'د.إ',
    ars: '$',
    aud: 'A$',
    bdt: '৳',
    bhd: '.د.ب',
    bmd: '$',
    brl: 'R$',
    cad: 'C$',
    chf: 'CHF',
    clp: '$',
    cny: '¥',
    czk: 'Kč',
    dkk: 'kr',
    eur: '€',
    gbp: '£',
    gel: '₾',
    hkd: 'HK$',
    huf: 'Ft',
    idr: 'Rp',
    ils: '₪',
    inr: '₹',
    jpy: '¥',
    krw: '₩',
    kwd: 'د.ك',
    lkr: 'Rs',
    mmk: 'K',
    mxn: '$',
    myr: 'RM',
    ngn: '₦',
    nok: 'kr',
    nzd: 'NZ$',
    php: '₱',
    pkr: '₨',
    pln: 'zł',
    rub: '₽',
    sar: '﷼',
    sek: 'kr',
    sgd: 'S$',
    thb: '฿',
    try: '₺',
    twd: 'NT$',
    uah: '₴',
    vef: 'Bs',
    vnd: '₫',
    zar: 'R',
    xdr: 'XDR',
    xag: 'XAG',
    xau: 'XAU',
    bits: 'μBTC',
    sats: 'sats'
};

export const COIN_SYMBOLS = {
    bitcoin: '₿',
    ethereum: 'Ξ',
    ripple: '✕',           // Often used for XRP
    tether: '₮',           // Not official, but commonly used
    binancecoin: 'Ⓑ',
    solana: '◎',
    'usd-coin': '$',       // It's a stablecoin pegged to USD
    dogecoin: 'Ð',
    'staked-ether': 'Ξ',   // Same as ETH
    cardano: '₳',
    tron: 'Τ',
    hyperliquid: 'H',      // No widely used symbol; custom
    'wrapped-bitcoin': '₿',
    'wrapped-steth': 'Ξ',
    stellar: '★',
    sui: 'S',              // No official symbol
    chainlink: '🔗',
    'wrapped-beacon-eth': 'Ξ',
    'hedera-hashgraph': 'ℏ',  // h-bar
    'wrapped-eeth': 'Ξ',
    'avalanche-2': '🄰',
    'bitcoin-cash': 'Ƀ',
    'shiba-inu': '🐶',
    litecoin: 'Ł',
    'leo-token': '🦁',
    weth: 'Ξ',
    toncoin: '🔵',         // unofficial (TON logo is a blue circle)
    stableusd: '$',
    'binance-usd': '$',
    'ethena-usde': '₮'     // Stablecoin, similar to USDT
};
